---
- name: "Slurp the precedent configuration."
  become: yes
  ansible.builtin.slurp:
    src: "{{ teleport_config_path }}"
  register: old_conf_raw

- name: "Set the precedent configuration as a fact."
  ansible.builtin.set_fact:
    old_conf: "{{ old_conf_raw['content'] | b64decode | from_yaml }}"

- name: "Flush the teleport client information when the auth token has changed."
  when: teleport_auth_token != ""
  notify: Reload_Teleport
  become: yes
  block:
    - name: "Stop teleport service if enabled"
      ansible.builtin.systemd:
        name: "teleport"
        state: "stopped"
      when:
        - not is_container

    - name: "Delete teleport data"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/var/lib/teleport/proc/sqlite.db"
        - "/var/lib/teleport/host_uuid"

- name: "Set fact teleport_auth_token from precedent configuration" # noqa no-handler
  ansible.builtin.set_fact:
    teleport_auth_token: "{{ old_conf.teleport.auth_token }}"
  when:
    - teleport_auth_token == ""
    - old_conf.teleport.auth_token is defined
    - old_conf.teleport.auth_token != ""

- name: "Set fact teleport_ca_pin from precedent configuration"
  ansible.builtin.set_fact:
    teleport_ca_pin: "{{ old_conf.teleport.ca_pin }}"
  when:
    - teleport_ca_pin == ""
    - old_conf.teleport.ca_pin is defined
    - old_conf.teleport.ca_pin != ""
