---
- name: "Manage teleport via archive"
  become: true
  when: teleport_installed.rc in [1,2] or teleport_update
  block:
    - name: Unarchive teleport
      ansible.builtin.unarchive:
        src: "{{ teleport_url }}"
        dest: "/tmp"
        remote_src: yes

    - name: Install teleport
      ansible.builtin.command:  # noqa no-changed-when
        cmd: ./install
      args:
        chdir: /tmp/teleport
      notify: Reload_Teleport
